server:
  port: 8072
  eureka:
    instance:
      preferIpAddress: true
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://eureka-server:8761/eureka/
spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
  zipkin:
    base-url: http://zipkin:9411
management:
  endpoints:
    web:
      exposure:
        include: '*'