spring:
  application:
    name: eurekaServer
  zipkin:
    base-url: http://zipkin:9411
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false