spring:
  application:
    name: eventAnnouncements
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true