spring:
  application:
    name: eventAnalysis
  zipkin:
    base-url: http://localhost:9411
  data:
    mongodb:
      uri: mongodb://localhost:27017/event-analysis


server:
  port: 8085


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true