eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  zipkin:
    base-url: http://localhost:9411
spring:
  application:
    name: notifications

server:
  port: 8088