spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/orders
  application:
    name: orders
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8082
  zipkin:
    base-url: http://localhost:9411