spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/tickets
  application:
    name: tickets
  zipkin:
    base-url: http://zipkin:9411
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true